package co.reto5.informesminviviendaGUI;

import java.sql.*;
import co.reto5.informesminviviendaDAL.conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D3V3L0P3R
 */
public class frmInformesMinVivienda extends javax.swing.JFrame {

    

    public frmInformesMinVivienda() {
        initComponents();
        setIconImage(getIconImage());
        
        PanelInforme1 panelInforme1 = new PanelInforme1();
        ShowPanel(panelInforme1);
    }
    
    //Icono del JFrame
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Images/Buenaventura.png"));
        return retValue;
    }

    private void ShowPanel(JPanel p)   {
        p.setSize(629,281);
        p.setLocation(0, 0);
        
        panelTables.removeAll();
        panelTables.add(p, BorderLayout.CENTER);
        panelTables.revalidate();
        panelTables.repaint();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnInforme1 = new javax.swing.JButton();
        jBtnInforme2 = new javax.swing.JButton();
        jBtnInforme3 = new javax.swing.JButton();
        panelTables = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 121, 107));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnInforme1.setBackground(new java.awt.Color(0, 188, 212));
        jBtnInforme1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jBtnInforme1.setForeground(new java.awt.Color(33, 33, 33));
        jBtnInforme1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/lider.png"))); // NOI18N
        jBtnInforme1.setText("INFORME 1");
        jBtnInforme1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnInforme1MouseClicked(evt);
            }
        });
        jBtnInforme1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInforme1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnInforme1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 82, 130, 40));

        jBtnInforme2.setBackground(new java.awt.Color(0, 188, 212));
        jBtnInforme2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jBtnInforme2.setForeground(new java.awt.Color(33, 33, 33));
        jBtnInforme2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/proyecto.png"))); // NOI18N
        jBtnInforme2.setText("INFORME 2");
        jBtnInforme2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnInforme2MouseClicked(evt);
            }
        });
        jBtnInforme2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInforme2ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnInforme2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 82, 130, 40));

        jBtnInforme3.setBackground(new java.awt.Color(0, 188, 212));
        jBtnInforme3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jBtnInforme3.setForeground(new java.awt.Color(33, 33, 33));
        jBtnInforme3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ventas.png"))); // NOI18N
        jBtnInforme3.setText("INFORME 3");
        jBtnInforme3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnInforme3MouseClicked(evt);
            }
        });
        jBtnInforme3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnInforme3ActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnInforme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 82, 130, 40));

        panelTables.setBackground(new java.awt.Color(178, 223, 219));

        javax.swing.GroupLayout panelTablesLayout = new javax.swing.GroupLayout(panelTables);
        panelTables.setLayout(panelTablesLayout);
        panelTablesLayout.setHorizontalGroup(
            panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        panelTablesLayout.setVerticalGroup(
            panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        jPanel1.add(panelTables, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 640, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnInforme1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInforme1ActionPerformed
                
        PanelInforme1 panelInforme1 = new PanelInforme1();
        ShowPanel(panelInforme1);
    }//GEN-LAST:event_jBtnInforme1ActionPerformed

    private void jBtnInforme2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInforme2ActionPerformed
        PanelInforme2 panelInforme2 = new PanelInforme2();
        ShowPanel(panelInforme2);
    }//GEN-LAST:event_jBtnInforme2ActionPerformed

    private void jBtnInforme3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnInforme3ActionPerformed
        PanelInforme3 panelInforme3 = new PanelInforme3();
        ShowPanel(panelInforme3);
    }//GEN-LAST:event_jBtnInforme3ActionPerformed

    private void jBtnInforme1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInforme1MouseClicked
        jBtnInforme1.setBackground(new Color(0,150,136));
        jBtnInforme2.setBackground(new Color(0,188,212));
        jBtnInforme3.setBackground(new Color(0,188,212));
    }//GEN-LAST:event_jBtnInforme1MouseClicked

    private void jBtnInforme2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInforme2MouseClicked
        jBtnInforme2.setBackground(new Color(0,150,136));
        jBtnInforme1.setBackground(new Color(0,188,212));
        jBtnInforme3.setBackground(new Color(0,188,212));
    }//GEN-LAST:event_jBtnInforme2MouseClicked

    private void jBtnInforme3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnInforme3MouseClicked
        jBtnInforme3.setBackground(new Color(0,150,136));
        jBtnInforme2.setBackground(new Color(0,188,212));
        jBtnInforme1.setBackground(new Color(0,188,212));
    }//GEN-LAST:event_jBtnInforme3MouseClicked

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInformesMinVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInformesMinVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInformesMinVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInformesMinVivienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInformesMinVivienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnInforme1;
    private javax.swing.JButton jBtnInforme2;
    private javax.swing.JButton jBtnInforme3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelTables;
    // End of variables declaration//GEN-END:variables
}
