/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.reto5.informesminviviendaGUI;

import co.reto5.informesminviviendaDAL.conexion;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D3V3L0P3R
 */
public class PanelInforme2 extends javax.swing.JPanel {

    DefaultTableModel model;

    /**
     * Creates new form PanelInforme2
     */
    public PanelInforme2() {
        initComponents();
        String[] titulo = {"ID PROYECTO", "CONSTRUCTORA", "NÚMERO DE HABITACIONES", "CIUDAD"};
        model = new DefaultTableModel(null, titulo);
        tblInformeProyecto.setModel(model);

        mostrarDatos();
    }

    public void mostrarDatos() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        conexion objConexion = new conexion();

        try {

            ResultSet resultado = objConexion.consultarRegistros("SELECT ID_Proyecto, Constructora, Numero_Habitaciones, Ciudad\n"
                    + "FROM Proyecto\n"
                    + "WHERE Clasificacion=\"Casa Campestre\" AND \n"
                    + "(Ciudad=\"Santa Marta\" OR Ciudad=\"Cartagena\" OR Ciudad=\"Barranquilla\");");

            while (resultado.next()) {

                Object[] proyecto = {resultado.getInt("ID_Proyecto"),
                    resultado.getString("Constructora"),
                    resultado.getDouble("Numero_Habitaciones"),
                    resultado.getString("Ciudad")
                };

                model.addRow(proyecto);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInformeProyecto = new javax.swing.JTable();

        tblInformeProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInformeProyecto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInformeProyecto;
    // End of variables declaration//GEN-END:variables
}
