/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.reto5.informesminviviendaGUI;

import co.reto5.informesminviviendaDAL.conexion;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D3V3L0P3R
 */
public class PanelInforme3 extends javax.swing.JPanel {

    DefaultTableModel model;

    /**
     * Creates new form PanelInforme3
     */
    public PanelInforme3() {
        initComponents();
        String[] titulo = {"ID COMPRA", "CONSTRUCTORA", "BANCO VINCULADO"};
        model = new DefaultTableModel(null, titulo);
        tblInformeComprasPorProyecto.setModel(model);

        mostrarDatos();
    }

    public void mostrarDatos() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        conexion objConexion = new conexion();

        try {

            ResultSet resultado = objConexion.consultarRegistros("SELECT C.ID_Compra,P.Constructora, P.Banco_Vinculado\n"
                    + "FROM Compra C, Proyecto P\n"
                    + "WHERE C.ID_Proyecto=P.ID_Proyecto AND \n"
                    + "C.Proveedor=\"Homecenter\" AND P.Ciudad=\"Salento\";");

            while (resultado.next()) {

                Object[] proyecto = {resultado.getInt("ID_Compra"),
                    resultado.getString("Constructora"),                    
                    resultado.getString("Banco_Vinculado")
                };

                model.addRow(proyecto);
            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollComprasPorProyecto = new javax.swing.JScrollPane();
        tblInformeComprasPorProyecto = new javax.swing.JTable();

        tblInformeComprasPorProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollComprasPorProyecto.setViewportView(tblInformeComprasPorProyecto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollComprasPorProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollComprasPorProyecto, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollComprasPorProyecto;
    private javax.swing.JTable tblInformeComprasPorProyecto;
    // End of variables declaration//GEN-END:variables
}
