/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.reto5.informesminviviendaGUI;

import java.sql.*;
import co.reto5.informesminviviendaDAL.conexion;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D3V3L0P3R
 */
public class PanelInforme1 extends javax.swing.JPanel {

    DefaultTableModel model;

    /**
     * Creates new form panelInforme1
     */
    public PanelInforme1() {
        initComponents();

        String[] titulo = {"ID LIDER", "NOMBRE", "PRIMER APELLIDO", "CIUDAD RESIDENCIA"};
        model = new DefaultTableModel(null, titulo);
        tblInformesMinVivienda.setModel(model);

        mostrarDatos();
    }
    
    public void mostrarDatos() {
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        conexion objConexion = new conexion();

        try {
           
                ResultSet resultado = objConexion.consultarRegistros("SELECT L.ID_Lider, L.Nombre, L.Primer_Apellido, L.Ciudad_Residencia \n"
                        + "AS CR FROM Lider L ORDER BY CR ASC;");

                while (resultado.next()) {

                    Object[] lider = {resultado.getInt("ID_Lider"),
                        resultado.getString("Nombre"),
                        resultado.getString("Primer_Apellido"),
                        resultado.getString("CR")
                    };

                    model.addRow(lider);
                }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPanelInforme1 = new javax.swing.JScrollPane();
        tblInformesMinVivienda = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(452, 402));

        tblInformesMinVivienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPanelInforme1.setViewportView(tblInformesMinVivienda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPanelInforme1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 281, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPanelInforme1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 6, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPanelInforme1;
    private javax.swing.JTable tblInformesMinVivienda;
    // End of variables declaration//GEN-END:variables
}
